### ISSUE TITLE
Needs a way to exit early

### ISSUE THREAD

**Issue by ianor** [matthewmatician/xml-flow#1]
It would be great if there was a way to exit the process early, rather that have to wait until the end of stream event. If the data I'm looking for is in the first three lines of a 2GB xml file, I want to grab what I need and bail out, rather than wait for the rest of the file to get parsed.  I tried a couple of hacks, like calling .destroy() on the file stream or calling .emit('end') on the file stream, but both of them caused an error. Here's the stack trace:

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Unexpected end
    Line: 1
    Column: 602
    Char: >
        at error (<project-path-omitted>/node_modules/xml-flow/node_modules/sax/lib/sax.js:642:8)
        at end (<project-path-omitted>/node_modules/xml-flow/node_modules/sax/lib/sax.js:650:64)
        at Object.SAXParser.end (<project-path-omitted>/node_modules/xml-flow/node_modules/sax/lib/sax.js:149:24)
        at SAXStream.end (<project-path-omitted>/node_modules/xml-flow/node_modules/sax/lib/sax.js:234:16)
        at IncomingMessage.onend (_stream_readable.js:501:10)
        at IncomingMessage.g (events.js:180:16)
        at IncomingMessage.emit (events.js:117:20)
        at EventEmitter.<anonymous> (<project-path-omitted>/server/api/cluster/cluster.model.js:54:37)
        at EventEmitter.emit (events.js:95:17)
        at SAXStream.<anonymous> (<project-path-omitted>/node_modules/xml-flow/lib/xml-flow.js:69:17) 

Maybe I'm just missing something, in which case I welcome correction. Either way, great library! Works superbly!

**Comment by matthewmatician** [comment]
When dealing with files, the best thing to do is call fileStream.close();
When dealing with HTTP requests, it's a bit more odd. You can call request.abort() and it may stop the request mid-transfer. The 'res' stream doesn't have a close() method. 

Either way, to stop listening to the events coming from the parser, simply call flow.removeEventListener('tag:the-tag-name', yourListener);
